### ISSUE TITLE
Vile Dust and Soul Glass Conflict

### ISSUE THREAD

**Issue by Kryllyk** [FTBTeam/FTB-Omnia#37] opened 2020-04-16 05:10 UTC
You are currently unable to make Vile Dust(Soul Shards) by smelting Soul Sand as it just produces Soul Glass (Dark Utilities)

**Comment by Naxanria** [comment] 2020-04-16 08:21
Duplicate of https://github.com/FTBTeam/FTB-Omnia/issues/14

**Closed as completed by Naxanria** 2020-04-16 08:21 UTC
Labels: duplicate
