### ISSUE TITLE
Ratlantis dim is not being created on the server but in single player it is just fine

### ISSUE THREAD

**Issue by AngelicBeatz** [FTBTeam/FTB-Omnia#87] opened 2020-05-19 02:09 UTC
* **Modpack Version**: 
1.4.0 pack and server
* **Issue**: 
When players use the Ratlantis portal they instead are teleported close to spawn and end up crashing the server multiple times after walking a bit.
* **Link to Log or Crash File Paste**: 
this is the 1st time it happened: https://www.dropbox.com/s/mfevsgt1yw3xyr1/crash-2020-05-18_10.25.29-server.txt?dl=1

this is the 2nd time after a reboot because it stayed in a constant saving error till I came and killed it: https://www.dropbox.com/s/e97mm5mu9b1psq7/crash-2020-05-18_12.13.19-server.txt?dl=1

this is the 3rd time and this time I just told people to not use the portal: https://www.dropbox.com/s/v7egp31ii3vl263/crash-2020-05-18_12.21.15-server.txt?dl=1
* **Is it Repeatable?**: 
Yes
* **Mod/s Affected**: 
rats-5.2.2-1.15.2
* **Known Fix**: 
none thus far I have destroyed the portal and told players to wait and they will have 1st dibs I promise.

**Comment by dmdeanha** [comment] 2020-05-20 21:06
Definitely repeatable, throws out to the same point on the overworld dimension

**Comment by AlexModGuy** [comment] 2020-05-30 20:28
Caused by: java.lang.NullPointerException
	at be.nevoka.betterbedrockgenerator.utils.Utils.getDimId(Utils.java:18) ~[?:0.0.6] {re:classloading}
	at be.nevoka.betterbedrockgenerator.BetterBedrockGenerator.shouldModifyBedrock(BetterBedrockGenerator.java:34) ~[?:0.0.6] {re:mixin,re:classloading}
	at net.minecraft.world.gen.NoiseChunkGenerator.handler$zze000$makeBedrock(NoiseChunkGenerator.java:532) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:assets/betterbedrockgenerator/betterbedrockgenerator.mixins.json:MixinFlattenBedrock,pl:mixin:A}


not a rats issue.

**Comment by Sunekaer** [comment] 2020-06-08 22:14
From testing this seems to be fixed in dev

**Closed as completed** 2020-06-10 23:13 UTC
Labels: bug, Fixed in dev
