### ISSUE TITLE
Clicking refresh for the server list crash client side

### ISSUE THREAD

**Issue by AngelicBeatz** [FTBTeam/FTB-Omnia#90] opened 2020-05-20 15:22 UTC
* **Modpack Version**: 
1.4.0 1.3.0 1.2.0
* **Issue**: 
when I go to the multiplayer screen I click on a server login but when I disconnect and wait for the server to reload I press the refresh button and it doesn't crash but if you have a server selected and click out outside of the selection box then click refresh it crashes the client.
* **Link to Log or Crash File Paste**: 
https://www.dropbox.com/s/1smna69rmswbkge/crash-2020-05-20_11.18.14-client.txt?dl=1
* **Is it Repeatable?**: 
yes
* **Mod/s Affected**: 
client side no mods
* **Known Fix**: 
do not know

**Comment by Naxanria** [comment] 2020-05-20 20:31
duplicate of #60

**Closed as completed by Naxanria** 2020-05-20 20:31 UTC
Labels: bug, duplicate
