### ISSUE TITLE
Crash on load immidiately

### ISSUE THREAD

**Issue by nstephenh** [FTBTeam/FTB-Omnia#51] opened 2020-04-27 15:50 UTC
I can't load any modpacks. Don't entirely know what the reason is. as the crash isn't very helpful. Might be my version of java but I thought the minecraft launcher had its own version. 
* **Modpack Version**: Omnia 1.2.0 and revelations

* **Issue**: pack fails to load

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/f7f60fe9

* **Is it Repeatable?**: Yes

**Comment by Sunekaer** [comment] 2020-04-27 16:08
Duplicate of https://github.com/FTBTeam/FTB-Omnia/issues/1

Theres nothing we can do about this issue, don't touch the window while the game is loading is the best tip

**Closed as completed by Sunekaer** 2020-04-27 16:08 UTC
Labels: bug, duplicate

**Comment by nstephenh** [comment] 2020-04-27 16:23
Oops I meant to post this in the ftb launcher. I didn't touch the window, so I'm not sure what happened.

**Comment by nstephenh** [comment] 2020-04-28 12:32
Update: Downgraded to 1.1.0 and the game loads properly, then reloaded the game with 1.2.0 and it loaded properly.
