### ISSUE TITLE
v1.2.0 bringing up console crashes the game

### ISSUE THREAD

**Issue by jfbarras** [FTBTeam/FTB-Omnia#50] opened 2020-04-26 00:05 UTC
* **Modpack Version**: 1.2.0

* **Issue**: If I press / to bring up the console, the game crashes with java.lang.ArrayIndexOutOfBoundsException: 1

* **Link to Log or Crash File Paste**: 
[crash-2020-04-25_19.52.47-client.txt](https://github.com/FTBTeam/FTB-Omnia/files/4534392/crash-2020-04-25_19.52.47-client.txt)

* **Is it Repeatable?**: Yes, I get it 3x in a row

* **Mod/s Affected**: Seems to be minetogether

* **Known Fix**: Unknown

**Comment by Naxanria** [comment] 2020-04-26 07:52
https://github.com/CreeperHost/CreeperHostGui/issues/237

**Comment by Naxanria** [comment] 2020-04-26 07:52
Duplicate of #49

**Closed as completed by Naxanria** 2020-04-26 07:52 UTC
Labels: bug, duplicate
