### ISSUE TITLE
Problem with Storage Drawers

### ISSUE THREAD

**Issue by Lord-Volkner** [FTBTeam/FTB-Omnia#145] opened 2020-09-12 21:17 UTC
* **Modpack Version**: 1.7.0

* **Issue**: Locked Storage Drawers loose the item if quantity goes to zero. The item will remain locked as long as the chunk remains loaded, but if the chunk is unloaded and reloaded, the drawer will retain it's locked status, but will no longer be locked on that item.

* **Is it Repeatable?**: Yes, it happens every time.

**Comment by Sunekaer** [comment] 2020-09-13 16:06
Duplicate of #17

**Closed as completed by Sunekaer** 2020-09-13 16:06 UTC
Labels: bug, duplicate
