### ISSUE TITLE
Over lapping recipe 

### ISSUE THREAD

**Issue by az2744** [FTBTeam/FTB-Omnia#96] opened 2020-05-23 15:57 UTC
There is an overlapping recipe. The soul sand when in a furnace smelts into glass, but it  also has a second available output. (but it doesn't work)
![soul sand issue](https://user-images.githubusercontent.com/65822423/82735009-5ff2c680-9cd3-11ea-916c-a86d20126da6.png)

**Comment by Mysteriosis** [comment] 2020-05-27 23:30
Duplicate of #83

**Closed as completed** 2020-05-28 07:54 UTC
Labels: duplicate
